// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owfxtjttfnizwtwegyqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93Znh0anR0Zm5pend0d2VneXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Mjg3MjksImV4cCI6MjA3MDIwNDcyOX0.zyF1Zqa9p-6j1VY8EB3En3dxjkLU9X2ljUM4CL9ooBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});